openapi: 3.0.0
info:
  title: Express-blog application
  description: A blog application created with React, MongoDB, NodeJS, Express
  version: 1.1.0
  contact:
    email: amal.thms@gmail.com
    
servers:
  - url: "{protocol}://localhost:5000/api/{version}"
    description: for local host 
    variables:
      version:
        enum:
          - v1
          - v2          
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /:
    get:
      tags:
        - String
      summary: returns a greet message from express
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error  
  /register:
    post:
      tags:
        - String
      summary: register a new user
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
  /login:
    post:
      tags:
        - String
      summary: login for user
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
   
